const produtos = [
  // Buquês - Rosas e Girassóis
  {
    id: 1,
    nome: "1 Rosa ou Girassol Solto",
    categoria: "Buquês",
    preco: 15.00,
    descricao: "Uma rosa ou girassol solto, perfeito para um gesto especial.",
    emoji: "🌹",
  },
  {
    id: 2,
    nome: "1 Rosa ou Girassol Embalado",
    categoria: "Buquês",
    preco: 30.00,
    descricao: "Uma rosa ou girassol com embalagem especial.",
    emoji: "🌹",
  },
  {
    id: 3,
    nome: "2 Rosas ou Girassóis",
    categoria: "Buquês",
    preco: 60.00,
    descricao: "2 rosas, 2 girassóis ou um de cada.",
    emoji: "💐",
  },
  {
    id: 4,
    nome: "3 Rosas ou Girassóis",
    categoria: "Buquês",
    preco: 80.00,
    descricao: "Buquê com 3 rosas ou girassóis.",
    emoji: "💐",
  },
  {
    id: 5,
    nome: "5 Rosas ou Girassóis",
    categoria: "Buquês",
    preco: 130.00,
    descricao: "Buquê com 5 rosas ou girassóis.",
    emoji: "💐",
  },
  {
    id: 6,
    nome: "6 Rosas ou Girassóis",
    categoria: "Buquês",
    preco: 170.00,
    descricao: "Buquê com 6 rosas ou girassóis.",
    emoji: "💐",
  },
  {
    id: 7,
    nome: "12 Rosas",
    categoria: "Buquês",
    preco: 250.00,
    descricao: "Buquê especial com 12 rosas.",
    emoji: "🌹",
  },
  {
    id: 8,
    nome: "12 Girassóis",
    categoria: "Buquês",
    preco: 250.00,
    descricao: "Buquê especial com 12 girassóis.",
    emoji: "🌻",
  },
  {
    id: 9,
    nome: "12 Rosas e Girassóis juntos",
    categoria: "Buquês",
    preco: 250.00,
    descricao: "Buquê especial com rosas e girassóis juntos.",
    emoji: "💐",
  },
  // Flores do Campo
  {
    id: 10,
    nome: "Flores do Campo Pequeno",
    categoria: "Buquês",
    preco: 120.00,
    descricao: "Buquê pequeno de flores do campo.",
    emoji: "🌼",
  },
  {
    id: 11,
    nome: "Flores do Campo Médio",
    categoria: "Buquês",
    preco: 160.00,
    descricao: "Buquê médio de flores do campo.",
    emoji: "🌼",
  },
  {
    id: 12,
    nome: "Flores do Campo Grande",
    categoria: "Buquês",
    preco: 200.00,
    descricao: "Buquê grande de flores do campo.",
    emoji: "🌼",
  },
  // Orquídeas
  {
    id: 13,
    nome: "Orquídea",
    categoria: "Orquídeas",
    preco: 90.00,
    descricao: "Orquídeas a partir de R$ 90,00. Consulte disponibilidade.",
    emoji: "🌸",
    consultarDisponibilidade: true,
  },
  // Box
  {
    id: 14,
    nome: "Box Pequeno",
    categoria: "Box",
    preco: 120.00,
    descricao: "Box pequeno com flores. Adicional de balão por R$ 30,00.",
    emoji: "🎁",
    adicionalBalao: true,
  },
  {
    id: 15,
    nome: "Box Médio",
    categoria: "Box",
    preco: 160.00,
    descricao: "Box médio com flores. Adicional de balão por R$ 30,00.",
    emoji: "🎁",
    adicionalBalao: true,
  },
  {
    id: 16,
    nome: "Box Grande",
    categoria: "Box",
    preco: 200.00,
    descricao: "Box grande com flores. Adicional de balão por R$ 30,00.",
    emoji: "🎁",
    adicionalBalao: true,
  },
  // Cestas Café da Manhã
  {
    id: 17,
    nome: "Cesta Café da Manhã Pequena",
    categoria: "Cestas",
    preco: 250.00,
    descricao: "Cesta de café da manhã pequena. Adicional Ferrero Rocher disponível.",
    emoji: "🧺",
    adicionalFerrero: true,
  },
  {
    id: 18,
    nome: "Cesta Café da Manhã Média",
    categoria: "Cestas",
    preco: 270.00,
    descricao: "Cesta de café da manhã média. Adicional Ferrero Rocher disponível.",
    emoji: "🧺",
    adicionalFerrero: true,
  },
  {
    id: 19,
    nome: "Cesta Café da Manhã Grande",
    categoria: "Cestas",
    preco: 300.00,
    descricao: "Cesta de café da manhã grande. Adicional Ferrero Rocher disponível.",
    emoji: "🧺",
    adicionalFerrero: true,
  },
  // Cestas Diversas
  {
    id: 20,
    nome: "Cesta Diversa",
    categoria: "Cestas",
    preco: 160.00,
    descricao: "Cestas com balão, chocolate e ursos. A partir de R$ 160,00.",
    emoji: "🎀",
  },
];

export default produtos;